language: php

php:
  - 7.2

services:
  - xvfb

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - nvm install 10
  - nvm use 10
  - npm install
  - export DISPLAY=:99.0

script:
  - vendor/bin/phpunit
  - npm run test
  - php artisan dusk